name: Warrant
main: com.github.generaldon.Warrant
version: 0.0.1
author: GeneralDon
description: Created to give warrants to police.
commands:
    warrant:
        description: Main Warrant command.
        usage: /warrant
        permission: warrant.warrant
        permission-message: You don't have permission!